"""cd into a service directory then exec the given command.

Used by Procfile / honcho so each service starts with the correct working
directory (needed for relative imports, alembic.ini discovery, etc.).

Usage:
    python scripts/run_service.py <service-dir> <cmd> [args...]

Example (generated by Procfile):
    python scripts/run_service.py services/gate-service \
        .venv/Scripts/uvicorn app.main:app --host 127.0.0.1 --port 8001
"""

import os
import subprocess
import sys

svc_dir, *cmd = sys.argv[1:]
os.chdir(svc_dir)
sys.exit(subprocess.call(cmd))
